allure:
    {
      'allure_descrption': '',
      'allure_suite': 'saas',
      'allure_sub_suite': '初始化',
      'allure_feature': 'saas',
      'allure_story': '登录初始化'
    }
test:
-   name: 【企业初始化】——admin登录初始化
    request:
        url: api/v1/system/setting/config
        method: GET
        headers:
          Authorization: Bearer__${admin_token}
        body:
    sql_statement:
    extract:
        organizationId: $.currentUser.organization.id,
        organizationName: $.currentUser.organization.name,
        organizationPath: $.currentUser.organization.path,
        ent_url: $.redirectUri,
        ent_name: $.websiteTitle,
        adminId: $.currentUser.id
        adminName: $.currentUser.fullName
    validate:
        -   eq:  [$.redirectUri, '${ent_url}']

-   name: 【企业初始化】——student登录初始化
    request:
        url: api/v1/system/setting/config
        method: GET
        headers:
          Authorization: Bearer__${student_token}
        body:
    sql_statement:
    extract:
        studentId: $.currentUser.id
        studentName: $.currentUser.fullName
    validate:
        -   eq:  [$.redirectUri, '${ent_url}']
