allure:
    {
      'allure_descrption': '',
      'allure_suite': '',
      'allure_sub_suite': '',
      'allure_feature': '',
      'allure_story': ''
    }
test:
-   name: 【企业初始化】——admin登录初始化
    request:
        url: api/v1/system/setting/config
        method: GET
        headers:
          Authorization: Bearer__${admin_token}
        params:
    sql_statement:
    extract:
        organizationId: $.currentUser.organization.id,
        organizationName: $.currentUser.organization.name,
        organizationPath: $.currentUser.organization.path,
        ent_url: $.redirectUri,
        ent_name: $.websiteTitle,
        adminId: $.currentUser.id
    validate:
        -   eq:  [$.redirectUri, '${ent_url}']

-   name: 【企业初始化】——student登录初始化
    request:
        url: api/v1/system/setting/config
        method: GET
        headers:
          Authorization: Bearer__${student_token}
        params:
    sql_statement:
    extract:
        studentId: $.currentUser.id
    validate:
        -   eq:  [$.redirectUri, '${ent_url}']
