##   online环境
#ent_url: http://zlzxy.zhixueyun.com/
#env_url: https://zxy9.zhixueyun.com
#config_url: https://zlzxy.zhixueyun.com/api/v1/system/setting/config
#
##   登录配置
#login_url: https://zxy9.zhixueyun.com/oauth/api/v1/auth
#organization_id: wzmvOswUFeB4wDUKA6S4fX+EQ7PHsBaI3Asb3Y61N2XzW2r2PD1Vzypz4BoloYqx
#login_method: JZNm+1f9txtGtiE0oRMJ1g==
#
##   admin登录配置
#admin_login_key: oZImo5zozQggF2BymfTc090trJ3N6xyWfo18/8Lp7jTh8l2v5iCDg5phuOMsAthCWpnEJqsiMBtxMaMJ+1oBvaY4o9ONCHnNuQ636V9wYD1tKdQ2akRai87xWqx8/jG8G7pbw4lBPjuvu21apMwevjpakgS+RyHMcb4FOWwRqeOSfE7VrI3v1WuuNxnSoWQ7l/iJtuOsDvdylsrG9xkoFjNv9FJW3m+z+bA964RyVTQ=
#admin_username: admin2
#admin_password: zxy123456
#
##   student登录配置
#student_login_key: oZImo5zozQggF2BymfTc090trJ3N6xyWfo18/8Lp7jTh8l2v5iCDg5phuOMsAthCWpnEJqsiMBtxMaMJ+1oBvaY4o9ONCHnNuQ636V9wYD1tKdQ2akRai87xWqx8/jG8G7pbw4lBPjuvu21apMwevjpakgS+RyHMcb4FOWwRqeOSfE7VrI3v1WuuNxnSoWQ7l/iJtuOsDvdylsrG9xkoFjNv9FJW3m+z+bA964RyVTQ=
#student_username: tests1
#student_password: zxy123456
#
##   mysql数据库的连接信息
#db_config:
#  {
#    db_host: 120.27.193.70,
#    db_name: 'testadmin',
#    db_password: 'dreamtech@.IT2021',
#    db_port: 4002,
#    db_charset: 'utf8'
#  }
#
##   redis数据库的连接信息
#redis_config:
#  {
#    redis_host: 192.168.10.46,
#    redis_port: 6379,
#    redis_password: ".com"
#  }