#   pre环境
ent_url: http://pre-202108-10.zhixueyun.com/
ent_host: 127.0.0.1:56894

#   登录配置
login_url: https://prezxy9.zhixueyun.com/oauth/api/v1/auth
login_key: 0J5Zm+UKb3i4gKYSpDJeGReXokKz1TeyyXGeeqJTfVxWhOz0DpdFdJmMvNNB8difW98CJNYk/1yZ6VYNw30SQtiPAOJLgVrkZolnP78WjJ5gtYuAYtUY3xMUMxcGgnQH2XP/biozhREJBQ9oJe9JKen7YehtDKiILw66buxAGorzXV6l2ChiSflP1Cq9QJomvbgm4oK6k6IfN1R9gDd+bA==
organization_id: 8oQHLQ76uGyWpBoRjG99q9BeEOYGyAcrnJKwZuMyb+nTGbKlVRloluSsZWDJNxri
login_method: JZNm+1f9txtGtiE0oRMJ1g==
remember: U5odry+hxJVf/JHFehA/oA==
username: admin
password: zxy123456

#   获取config
config_url: https://pre-202108-10.zhixueyun.com/api/v1/system/setting/config

#   mysql数据库的连接信息
db_config:
  {
    db_host: 120.27.193.70,
    db_name: 'testadmin',
    db_password: 'dreamtech@.IT2021',
    db_port: 4002,
    db_charset: 'utf8'
  }

#   redis数据库的连接信息
redis_config:
  {
    redis_host: 192.168.10.46,
    redis_port: 6379,
    redis_password: ".com"
  }