#   test环境
ent_url: https://tester1.zhixueyun.com/
ent_host: http://47.97.36.217:443
config_url: https://tester1.zhixueyun.com/api/v1/system/setting/config

#   登录配置
login_url: https://test9.zhixueyun.com/oauth/api/v1/auth
organization_id: SfGRfmj5IJiUyHP+luX/iFcGsyTV5dq8abfvRl+0W1uh7y45djf3lsHagGfQ7ilC
login_method: JZNm+1f9txtGtiE0oRMJ1g==

#   admin登录配置
admin_login_key: 0J5Zm+UKb3i4gKYSpDJeGReXokKz1TeyyXGeeqJTfVxWhOz0DpdFdJmMvNNB8difW98CJNYk/1yZ6VYNw30SQtiPAOJLgVrkZolnP78WjJ5UdLpbOFCXvxy6PWmdAjopFj+3wVtARcQ8o6Qx+miPgw36InzJC7ETJj9RgfuiFoZHAxiQuHrHaNUIh3fxZVLawMDGI/ZPHSzaISUKK9gKNw==
admin_username: admin
admin_password: zxy123456

#   student登录配置
student_login_key: 0J5Zm+UKb3i4gKYSpDJeGReXokKz1TeyyXGeeqJTfVxWhOz0DpdFdJmMvNNB8difW98CJNYk/1yZ6VYNw30SQtiPAOJLgVrkZolnP78WjJ5UdLpbOFCXvxy6PWmdAjopFj+3wVtARcQ8o6Qx+miPgw36InzJC7ETJj9RgfuiFoYQgMDfhLlBuduz0dA9IlEnR3TnXNzjIZ7oBQMDwuFsrDYtI++jgeRxPoF3Ufaghug=
student_username: test_1
student_password: zxy123456

#   mysql数据库的连接信息
db_config:
  {
    db_host: 120.27.193.70,
    db_name: 'testadmin',
    db_password: 'dreamtech@.IT2021',
    db_port: 4002,
    db_charset: 'utf8'
  }

#   redis数据库的连接信息
redis_config:
  {
    redis_host: 192.168.10.46,
    redis_port: 6379,
    redis_password: ".com"
  }